export const PcLocators = {
  urls: {
    onAirGiftOrder: 'custord/present/orderSheet',
    onAirBuyOrder: 'custord/orderSheet',
    productDetail: 'display/product',
    myLikePage: 'https://www.kshop.co.kr/display/shoppingHistory/product?tab=like',
  },
  main: {
    navItems: '//nav//li',  // 상단 네비게이션 항목 (9개)
    mainArea: '//main',     // 페이지 본문 영역
    onAirButton: '//button[contains(@class,"FloatingBannerActions_btnOnAirLottie")]',
    onAirDisplay: '//div[contains(@class,"OnAirDisplay_wrap")]',
    onAirDirectBuyButton: '//div[contains(@class,"OnAirProgram_btnArea")]//span',
    onAirDirectBuyFirstOption: '//div[contains(@class,"SelectBox_optionList")]/div',
    onAirDirectBuySecondOption: '//button[contains(@class,"SelectBox_option")]',
    onAirGiftButton: '//div[contains(@class,"ButtonPurchase")]//span[text()="선물하기"]',
    onAirProductName: '//div[contains(@class,"prodOptionTitle")]//strong',
    onAirCartButton: '//div[contains(@class,"ButtonPurchase")]//span[text()="장바구니"]',
    onAirCartMoveButton: '//span[text()="바로가기"]',
    cartProductName: '(//button[contains(@class,"OrderProductItem_prodName")])[last()]',
    cartDeleteButton: '//span[text()="선택 삭제"]',
    onAirBuyButton: '//div[contains(@class,"ButtonPurchase")]//span[text()="구매하기"]',
    categoryButton: '//button[text()="카테고리"]',
    categoryOneDepthButton: '//div[contains(@class,"Modal")]//div[contains(@class,"Tab_wrap")]/div/button',
    categoryTwoDepthButton: '//div[contains(@class,"categoryList")]/a',
    homeShoppingThreeDepthButton: '//div[contains(@class,"SubCategoryMenu_inner")]/button',
    giftShowThreeDepthButton: '//ul[contains(@class,"Brands_list")]/li',
    categoryThreeDepthFilter: '//ul[contains(@class,"sortList")]/li/button',
    searchButton: '//div[contains(@class,"Header_right")]/a',
    popularWords: '//ul[contains(@class,"PopularWords")]//p',
    searchProduct: '(//div[contains(@class,"ProductItem_box")])[1]',
  },
  login: {
    loginButton: '//a[text()="로그인/회원 가입"]',
    idInput: '//input[@placeholder="아이디"]',
    pwInput: '//input[@placeholder="비밀번호"]',
    loginSubmitButton: '//span[text()="로그인"]',
    logoutButton: '//button[text()="로그아웃"]',
    certificationRequestButton: '//span[text()="인증요청"]',
  },
  product: {
    onAirVideo: '//div[contains(@class,"ModalOnAir_videoBox")]//video',
    alarmButton: '//button[contains(@class,"OnAirProgram_btnAlarm")]',
    broadcastNotificationPopupHeader: '//h3[text()="방송 알림 등록"]',
    broadcastNotificationRegisterButton: '//span[text()="방송 알림 등록하기"]',
    smsConsentCheckbox: '//label[contains(@class,"checkbox")]',
    myBroadcastNotificationButton: '//span[text()="내 방송알림보기"]',
    disableNotificationButton: '//span[text()="알림 해제"]',
    mdsPickProduct: '//div[contains(@class,"HeroBannerC_frame")]',
    productLikeButton: '(//div[contains(@class,"ProdActions_support")]//button)[1]',
    likePageLikeButton: '//div[contains(@class,"ProductItem_box")]/button',
    productDetailInfoTab: '(//div[contains(@class,"ProductTemplate_tab")]//button)[1]',
    productBuyInfoTab: '(//div[contains(@class,"ProductTemplate_tab")]//button)[2]',
    productReviewTab: '(//div[contains(@class,"ProductTemplate_tab")]//button)[3]',
    productQnaTab: '(//div[contains(@class,"ProductTemplate_tab")]//button)[4]',
    productDetailInfo: '//div[contains(@class,"ProdDetailInfo_wrap")]',
    productBuyInfo: '//div[contains(@class,"BuyDetailInfo_wrap")]',
    productReview: '//div[contains(@class,"ReviewDetailInfo_wrap")]',
    productQna: '//div[contains(@class,"ProdQnaDetail_wrap")]',
    optionBox: '//div[contains(@class,"SelectBox_item")]',
    productName: '//div[contains(@class,"ProdTopInfo_title")]//strong',
  },
  quick: {
    onAirModalImg: '//button[contains(@class,"ModalOnAir")]//img',
    onAirDirectBuyButton: '//div[contains(@class,"ModalOnAir_buyBox")]//button',
    onAirProductName: '//div[contains(@class,"ModalOnAir_inner")]//em[contains(@class,"ProductItem_title")]',
  },
  my: {
    myButton: '//a[text()="마이"]',
    orderHistoryTab: '//div[contains(@class,"MyPage_menuList")]/div[1]//li[1]',
    orderList: '//div[contains(@class,"orderList")]',
    claimHistoryTab: '//div[contains(@class,"MyPage_menuList")]/div[1]//li[2]',
    giftShowTab: '//div[contains(@class,"MyPage_menuList")]/div[1]//li[3]',
    giftShowContent: '//div[contains(@class,"GiftShowPage_wrap")]',
    giftShowBalanceTab: '//div[contains(@class,"MyPage_menuList")]/div[1]//li[4]',
    giftShowBalanceContent: '//div[contains(@class,"GiftShowBalanceTemplate_wrap")]',
    taxListTab: '//div[contains(@class,"MyPage_menuList")]/div[1]//li[5]',
    taxListContent: '//div[contains(@class,"TaxListTemplate_wrap")]',
    deliveryAddressTab: '//div[contains(@class,"MyPage_menuList")]/div[2]//li[1]',
    deliveryAddressContent: '//div[contains(@class,"addressList")]',
    phoneAddressTab: '//div[contains(@class,"MyPage_menuList")]/div[2]//li[2]',
    phoneAddressContent: '//div[contains(@class,"PhoneAddress_wrap")]',
    refundAccountTab: '//div[contains(@class,"MyPage_menuList")]/div[2]//li[3]',
    refundAccountContent: '//div[contains(@class,"RefundAccountList_wrap")]',
    giftMessageTab: '//div[contains(@class,"MyPage_menuList")]/div[2]//li[4]',
    giftMessageContent: '//div[contains(@class,"GiftMessageMangmentTemplate_wrap")]',
    alphaPointTab: '//div[contains(@class,"MyPage_menuList")]/div[2]//li[5]',
    alphaPointContent: '//div[contains(@class,"AlphaPoint_box")]',
    ticketTab: '//div[contains(@class,"MyPage_menuList")]/div[2]//li[6]',
    ticketContent: '//div[contains(@class,"Ticket_box")]',
    broadcastNotificationTab: '//div[contains(@class,"MyPage_menuList")]/div[2]//li[7]',
    broadcastNotificationContent: '//div[contains(@class,"NotificationList")]',
    simpleLoginTab: '//div[contains(@class,"MyPage_menuList")]/div[2]//li[8]',
    simpleLoginContent: '//ul[contains(@class,"simpleLoginList")]',
    modifyCustomerInfoTab: '//div[contains(@class,"MyPage_menuList")]/div[2]//li[9]',
    modifyCustomerInfoContent: '//div[contains(@class,"ModifyCustInfo_wrap")]',
    benefitTab: '//div[contains(@class,"MyPage_menuList")]/div[2]//li[10]',
  }
};
